### ISSUE TITLE
Commands w/ Nicknames - "No player was found"

### ISSUE THREAD

**Issue by rajkundu** [InventivetalentDev/NickNamer#105]
## What steps will reproduce the problem?  
1. Install NickNamer 3.17.0-SNAPSHOT
2. Install PacketListenerAPI 3.7.5-SNAPSHOT
3. Run Server
4. Set a player's nickname (e.g. my username "brolicecar" to the nickname "Raj")

## What were you expecting to happen? What happened instead?  
Tab autocompletion works perfectly, giving me a list of all nicknames. However, when I use a nickname in a command (e.g. `/tell Raj This plugin is great!`), I get the error message "No player was found." The server log shows that `brolicecar issued server command: /tell Raj This plugin is great!`

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
• `NickNamer version 3.17.0-SNAPSHOT`
• `PacketListenerApi version 3.7.5-SNAPSHOT`

## What Spigot version are you using? *Type /version*  
`CraftBukkit version git-Spigot-6de3d4b-a6f8093 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

## What plugins are you using? *Type /plugins*  
`Plugins (5): LuckPerms, SimpleCensor, AdvancedTeleport, PacketListenerApi, NickNamer`

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log* 
N/A

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Pretty simple survival server with friends - no Bungeecord. I really wish there were a way to get nicknames to practically replace player names, in all messages and in commands. It seems that this plugin works for everything except commands (at least in my case).

**Comment by rajkundu** [comment]
Any ideas? @InventivetalentDev

**Comment by InventivetalentDev** [comment]
enabling `replace.chat.in.command` in the config should help with that.

**Comment by rajkundu** [comment]
That does the opposite - if I type `/tell brolicecar This plugin is great!`, the server console shows `brolicecar issued server command: /tell Raj This plugin is great!` while in-game, I still get the error that "No player was found"

**Comment by InventivetalentDev** [comment]
I'm pretty sure this was possible in some way, try playing around with the config options.

**Comment by rajkundu** [comment]
I have already, unfortunately. Is this working for other people, and just not for me?

**Comment by EXOgreen** [comment]
nope, same issue. when trying to run commands on players, even TP, entities arent found. its not just you.

**Comment by EXOgreen** [comment]
I see the new release. man that was fast! ill check it out on my server this evening, but in a quick test it looked good!

Thanks!

**Comment by rajkundu** [comment]
Thank you! That was really fast.

Now an issue is, names work in commands but not in chat. E.g. It'll say `<brolicecar> Hello!` instead of `<Raj> Hello!`

Here's my config.yml:
```
replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: true
    in:
      # Replace real names in incoming commands with the player's nickname
      command: false
      # Replace incoming command nicknames with the player's real name
      # (If multiple players use the same nickname, it will default to the first available player's real name)
      commandReverse: true

      # Replace real names in general (non-command) incoming messages with the player's nickname
      general: true
      # Replace incoming nicknames with the player's real name
      # (If multiple players use the same nickname, it will default to the first available player's real name)
      generalReverse: false
  scoreboard: false
  scoreboardScore: false
  scoreboardTeam: false
  tabComplete:
    chat: false

updateSelf: true

random:
  join:
    nick: false
    skin: false
  nick:
  - "inventivetalent"
  - "md_5"
  - mojang: # Name category
    - "jeb_"
    - "Notch"
    - "Dinnerbone"
  skin:
  - "md_5"
  - "inventivetalent"
```
