### ISSUE TITLE
NickNamer compatibility with BedwarsRel

### ISSUE THREAD

**Issue by sebastianbinder** [InventivetalentDev/NickNamer#12]
Problem: Player is being nicked, as long as no team is selected. As soon as the player selects a team (see [method from BedwarsRel](https://github.com/BedwarsRel/BedwarsRel/blob/master/src/main/java/io/github/yannici/bedwars/Game/Team.java#L71)) playlist name is reset to original name - name above the player's head stays right (see screenshot below). Maybe this happens because of [this line](https://github.com/BedwarsRel/BedwarsRel/blob/master/src/main/java/io/github/yannici/bedwars/Game/Team.java#L76).

NickNamer: `NickNamer_v3.11.7.jar`
Used on Spigot Server in BungeeCord Network
This server is running CraftBukkit version git-Spigot-798f32d-0cd0397 (MC: 1.9.4)

``` yml
replace:
  chat:
    # Replace names in messages sent by players
    player: true

    # Replaces names in ALL outgoing messages
    out: true
    in:
      # Replace names in incoming commands
      command: true

      # Replace names in general (non-command) incoming messages
      general: true
  scoreboard: true
  scoreboardScore: true
  scoreboardTeam: true
  tabComplete:
    chat: true
```

![2016-06-30_14 30 41](https://cloud.githubusercontent.com/assets/5227469/16488152/636c17d2-3ecf-11e6-82b1-6b5759d0b775.png)
