### ISSUE TITLE
Using NickNamer with EssentialsXChat

### ISSUE THREAD

**Issue by wgetgoose** [InventivetalentDev/NickNamer#121]
## What steps will reproduce the problem?  
1. Install NickNamer, EssentailsX, and EssentialsXChat
2. Disable EssentialsX nickname feature and rebind using aliases.
3. /nickname binds to NickNamer, but /nick can't seem to work
## What were you expecting to happen? What happened instead?  
Expecting /nick to use NickNamer's /nick, instead just shows "disabled"
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Nicknamer: 3.18.2 Snapshot, EssentialsX: 2.17.2.77, EssentialsXChat: 2.17.2.77
## What Spigot version are you using? *Type /version*  
git-Paper-261
## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/64772046/81441162-209a7680-9126-11ea-9e20-cb27aad20c35.png)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Tried solution [here](https://github.com/InventivetalentDev/NickNamer/issues/113), no success. Commands.yml seen below
```
command-block-overrides: []
aliases:
    nickname:
    - "nicknamer:nick $1-"
    nick:
    - nickname $1-
    away:
  - essentials:afk 
```
and Config.yml in a pastebin [here](https://pastebin.com/N1H2aH9f)

Notes: I'm worried NickNamer won't work with EssentialsXChat, in the sense that displaynames will not output to the chat because EssentialsXChat is trying to read displaynames from Essentials. I am unsure of how to change where EssentialsXChat reads names from. I also can't quite figure out the aliases. Thanks!

**Comment by GooseBinary** [comment]
Kind of fixed. Forgot to get Player API / PAPI ([here](https://www.spigotmc.org/resources/placeholderapi.6245/). I want to bind /nick to nicknamer's /nick. But, if I enable /nick in the Essentials config, it uses the Essentials nickname system. But if I disable /nick in the config, the alias doesn't work and nick is just "disabled." Any help would be super appreciated.

**Comment by Th3Shadowbroker** [comment]
Hey @GooseBinary,
I were unable to replicated your problem with the `/nick` command. I set everything up as I explained in #113 and everything worked as expected. The message I get when I'm using the nick command looks as follows:

*Essentials (No aliases setup, no command disabled)*:
![image](https://user-images.githubusercontent.com/8280615/81449148-e78ef000-917f-11ea-8275-0ecb086c60ca.png)

*NickNamer (Aliases setup, nickname command disabled)*:
![image](https://user-images.githubusercontent.com/8280615/81449173-f70e3900-917f-11ea-90dc-7b222ec66428.png)

Regarding the chat thingy:
During my tests NickNamer worked fine with EssentialsXChat, after enabling the option to replace names in all outgoing messages. (`replace > chat > out`)

**Comment by GooseBinary** [comment]
Can you show me your aliases exactly? Also, can I see your #disabled-commands in essentials? That would help a ton. Thanks!

**Comment by GooseBinary** [comment]
Here are both of mine now for reference:
     Commands.yml
```
command-block-overrides: []
aliases:
    nickname:
    - "nicknamer:nickname $1-"
    nick:
  - nickname $1-
    away:
  - essentials:afk`
```
    config.yml disabled section
```
disabled-commands:
- nickname
```

**Comment by Th3Shadowbroker** [comment]
*commands.yml*
```yaml
command-block-overrides: []
aliases:
  icanhasbukkit:
  - version $1-
  nick:
  - nickname $1-
ignore-vanilla-permissions: false
```
`/nick` as well as `/nickname` work perfectly fine with this setup. **Without** this part:
```yaml
  nickname:
  - "nicknamer:nickname $1-"
```

*EssentialsX config.yml*
```yaml
...
disabled-commands:
   - nickname
...
```
